services:
  whisper-asr-webservice:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASR_MODEL=base
    ports:
      - "9010:9000"
    volumes:
      - ./app:/app/app
      - ./docker-entrypoint.sh:/app/docker-entrypoint.sh
      - cache-pip:/root/.cache/pip
      - cache-poetry:/root/.cache/poetry
      - cache-whisper:/root/.cache/whisper

volumes:
  cache-pip:
  cache-poetry:
  cache-whisper:
